{{- if not .Values.secrets.existingSecret }}
{{- $data := dict "CT_MASTER_KEY" .Values.secrets.masterKey "CT_ADMIN_KEY" .Values.secrets.adminKey "CT_SETUP_TOKEN" .Values.secrets.setupToken "CT_METRICS_TOKEN" .Values.secrets.metricsToken "CT_DATABASE_URL" .Values.database.url "CT_REDIS_URL" .Values.redis.url }}
{{- $set := dict }}
{{- range $k, $v := $data }}{{ if $v }}{{ $_ := set $set $k $v }}{{ end }}{{ end }}
{{- if $set }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "controltower.fullname" . }}
  labels:
    {{- include "controltower.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := $set }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
{{- end }}
