import { describe, expect, it } from 'vitest';
import { inventoryCsv, inventoryMarkdown, type DataflowInventory } from '../src/admin/export.js';

const inv: DataflowInventory = {
  generated_at: Date.UTC(2026, 8, 23, 12, 0),
  window_hours: 24,
  enforcement: true,
  totals: { agents: 1, models: 1, mcp_servers: 1, paths: 2, requests: 12, spend_nanousd: 2_500_000_000, gates: 1 },
  agents: [{ id: 'k', name: 'sdr-agent', team: 'sales', project: null, zones: ['Sales'], models_allowed: ['*'], tools_allowed: ['crm__*'], requests: 12, spend_nanousd: 2_500_000_000, last_used: null }],
  models: [{ id: 'd', name: 'smart', upstream: 'gpt-4o', provider: 'OpenAI', provider_kind: 'openai', zones: [], requests: 10 }],
  mcp_servers: [{ id: 'm', name: 'CRM', url: 'https://crm.example.com/mcp', health: 'ok', zones: ['CRM'], tools: [{ name: 'delete_contact', operation: 'admin' }] }],
  paths: [
    { agent: 'sdr-agent', agent_id: 'k', team: 'sales', kind: 'model', target: 'smart', target_id: 'd', provider: 'OpenAI', tool: null, operation: null, requests: 10, errors: 1, blocked: 0, held: 0, spend_nanousd: 2_500_000_000, tokens: 900, last_seen: Date.UTC(2026, 8, 23, 11, 0), access: 'allow', access_gate: null, inspected_by: ['Block secrets'], key_permits: true },
    { agent: 'sdr-agent', agent_id: 'k', team: 'sales', kind: 'tool', target: 'CRM', target_id: 'm', provider: 'MCP', tool: 'delete_contact', operation: 'admin', requests: 2, errors: 0, blocked: 0, held: 2, spend_nanousd: 0, tokens: 0, last_seen: Date.UTC(2026, 8, 23, 11, 30), access: 'hold', access_gate: 'Deletes need approval, "always"', inspected_by: [], key_permits: false },
  ],
  gates: [{ id: 'g', name: 'Deletes | approval', effect: 'require_approval', covers: 'any agent → CRM', enabled: true, hits: 2 }],
  zones: [{ id: 'z', name: 'CRM', members: 1 }],
};

describe('data-flow inventory export', () => {
  it('writes a CSV with quoting and USD', () => {
    const csv = inventoryCsv(inv).trim().split('\n');
    expect(csv[0]).toBe('agent,team,kind,target,provider,tool,operation,requests,errors,blocked,held,spend_usd,tokens,access,access_gate,inspected_by,key_permits,last_seen_utc');
    expect(csv[1]).toBe('sdr-agent,sales,model,smart,OpenAI,,,10,1,0,0,2.500000,900,allow,,Block secrets,true,2026-09-23T11:00:00.000Z');
    expect(csv[2]).toContain(',hold,"Deletes need approval, ""always""",,false,');
  });

  it('writes Markdown tables that survive pipes, and flags paths the key does not allow', () => {
    const md = inventoryMarkdown(inv);
    expect(md).toContain('# Agent data-flow inventory');
    expect(md).toContain('Generated by Control Tower on 2026-09-23 12:00 UTC, covering the last 24 hours. Enforcement is **on**.');
    expect(md).toContain('| sdr-agent | CRM → delete_contact (admin) | MCP | 2 | 0 | 0 | 2 | — | needs approval (Deletes need approval, "always") | — | **no** |');
    expect(md).toContain('| Deletes \\| approval | require approval | any agent → CRM | yes | 2 |');
  });
});
